# Generated by Django 5.0.4 on 2024-05-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_delete_shippingaddress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
