# Generated by Django 5.0.4 on 2024-05-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_customer_email_alter_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="digital",
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="purchase",
            field=models.IntegerField(default=0),
        ),
    ]
